package ERP.model;

public enum TipoLogginEnum {
	GERENTE,ADMINISTRADOR, PSICOLOGO,DIRECTOR_RECURSOS_HUMANOS, JEFE_FNB,
	JEFE_VENTAS_Y_CONSUMO, EMPLEADO_PROFESIONAL, JEFE_SERVICIO_AL_CLIENTE,
	GESTOR_CALL_CENTER,GESTOR_SERVICIO_CLIENTE, AUXILAR_SAC, AUXILIAR_OPERACIONES_DOMICILIARIAS,
	PROFESIONAL_DE_FACTURACION, AUXILIAR_FACTURACION,PROFESIONAL_NOMINA, COORDINADOR_SAC,
	JEFE_MANTENIMIENTO, INGENIERO_GASODUCTO, AUXILIAR_GASODUCTO,
	TECNICO_HARDWARE, TECNICO_SOFTWARE, INGENIERO_SISTEMAS,PLANEACION


}
